### PR TITLE
fix(domain): add default headers in Response

### LINKED ISSUE #38: Embed standard Http headers directly into FullHttpResponse
Add support for the following headers.
- [ ] Date
- [ ] Server

### PR DESCRIPTION
**Pull request by amitksingh1490**
Fixes #38

### CODE REVIEW

File: zio-http/src/main/scala/zhttp/http/Response.scala [hunk 1]
```diff
@@ -59,8 +61,10 @@ object Response {
     status: Status = defaultStatus,
     headers: List[Header] = defaultHeaders,
     content: HttpContent[Any, String] = defaultContent,
-  ): Response =
-    HttpResponse(status, headers, content)
+  ): Response = {
+    val createDate: String = DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now)
+    HttpResponse(status, headers concat List(Header(JHttpHeaderNames.DATE, s"$createDate")), content)
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/http/Response.scala:66]: This is making the function impure.

**Review by tusharmath — CHANGES_REQUESTED** [review]

File: zio-http/src/main/scala/zhttp/http/Response.scala [hunk 2]
```diff
@@ -34,6 +36,8 @@ object Response {
       val jContentBytBuf = res.content match {
         case HttpContent.Complete(data) =>
           jHttpHeaders.set(JHttpHeaderNames.CONTENT_LENGTH, data.length())
+          jHttpHeaders.set(JHttpHeaderNames.SERVER, "zio-http")
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/http/Response.scala:39]: `zio-http` can be moved up so that the string is allocated only once.

**Review by tusharmath — CHANGES_REQUESTED** [review]

**Review by tusharmath — APPROVED** [review]
